spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_modeler
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: schema_version

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.db.modeler.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8010
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
  level:
    root: INFO
    com.db.modeler: DEBUG
  file:
    path: ./logs
    name: ${logging.file.path}/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 